Foodyzz/Foodyzz/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
]

Foodyzz/food/urls.py
from django.urls import path
from . import views

app_name='food'

urlpatterns = [
    path('',views.index,name='index' ),
    path('item/',views.item,name='item'),
    path('<int:item_id>/',views.detail,name='detail'),

    # add items
    path('add/',views.create_item,name="create_item"),
]

Foodyzz/food/models.py
from django.db import models

# Create your models here.
# python manage.py migrate : It looks to all apps which are under the installed apps and create necessary database tables according to the database settings in setting.py file.

class Item(models.Model):
    def __str__(self):
        return self.item_name

    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

Foodyzz/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

Foodyzz/food/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Item
from django.template import loader
from .forms import ItemForm

# Create your views here.

def index(request):
    item_list=Item.objects.all()
    # template=loader.get_template('food/index.html')
    context={
        'item_list':item_list,
    }
    # return HttpResponse(template.render(context,request))
    return render(request,'food/index.html',context
    )


def item(request):
    return HttpResponse("<h1>Hii PRITIREKHA</h1>")

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    # return HttpResponse("This is item number/id : %s" %  
    # item_id)
    return render(request,'food/detail.html',context)


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')  

    return render(request, 'food/item-form.html', {'form': form})

Foodyzz/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'food/style.css' %}" />
        {% comment %} bootstrap {% endcomment %}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossorigin="anonymous"
        ></script>
      </head>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Foodyz</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Delete Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View Item</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block body %}
      {% endblock %}
</body>
</html>

Foodyzz/food/templates/food/detail.html
{% extends 'food/base.html' %} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img height="200px" width="200px" src="{{item.item_image}}" alt="" class="card" />
    </div>
    <div class="col-md-6">
      <h1>{{ item.item_name }}</h1>
      <h2>{{ item.item_desc }}</h2>
      <h3>{{ item.item_price }}</h3>
    </div>
  </div>
</div>

{% endblock %}

Foodyzz/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index page</title>
  </head>

  <body>
    
    {% block body %} {% for item in item_list %} 

    <div class="row">
      <div class="col-md-3 offset-md-2">
          <img src="{{item.item_image}}" alt="" class="card" height="150px" width="150px">
      </div>
      <div class="col-md-4">
        <h3>{{item.item_name}}</h3>
        <h5>{{item.item_desc}}</h5>
        <h6>{{item.item_price}}</h6>
      </div>
      <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
      </div>
    </div>
    {% comment %} old code {%
    endcomment %}
    <ul>
      {% comment %}
      <a href="/food/{{item.id}}"
        ><li>{{ item.id }} ----- {{item.item_name}}</li></a
      >
      {% endcomment %}

      {% comment %} <a href="{% url 'food:detail' item.id %}"
        ><li>{{ item.id }} ----- {{item.item_name}}</li></a
      >
    </ul> {% endcomment %}

    {% endfor %} {% endblock %} {% comment %}
    <p>
      using hardcoded url makes things titely coupled approach means less
      dynamic , changing templates will be difficult .
    </p>

    <h2>Name spacing</h2>
    <p>
      If there are multiple apps and the name of the path is same so to avoid
      the conflict we will use here name space which is food:detail
    </p>
    {% endcomment %}
  </body>
</html>

Foodyzz/food/templates/food/item-form.html
<form action="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>